### ISSUE TITLE
[Core] Negated version of boost::hana::is_default

### ISSUE THREAD

**Issue by m-j-w** [boostorg/hana#199]
I realized all concepts make use of a negated `is_default` when looking for a valid specialization. Since that exclamation mark is easily overlooked leading to misinterpretation, a negated `is_not_default` might improve readability. Perhaps a `is_specialized`, `has_specialization` or `provides_specialization` might be even more clear in indicating the intent.
Also, in its definition, shouldn't the line `static_cast<default_>(*(Method*)0)` make use of `nullptr` ?

**Comment by ldionne** [comment]
You're right that `is_default` is always negated. I think that `is_implemented` would be more descriptive. Regarding the usage of `0` instead of `nullptr`; it's really just a nitpick, since I'm casting it to `Method*` anyway. I guess `nullptr` might be more idiomatic.

**Comment by ldionne** [comment]
Oh wait, `is_implemented` won't work, since a method can be implemented but with a default implementation. This is why I didn't use `is_implemented` in the first place, I think (I have already thought about this issue some time ago, but I had decided to keep negating `is_default`).

**Comment by ldionne** [comment]
Closing this, since I'm not convinced of the added value of `is_not_default` vs `!is_default`, and using something like `is_specialized` would sometimes be wrong, as explained above.

But just to expand on that, what I meant above is that since it is possible for an algorithm to be implemented (via a default implementation) without a container specializing it, `is_specialized` wouldn't say the right thing. Also, `is_implemented` would _also_ not work, since it could be the case that a "default" algorithm has no implementation, which is the case e.g. of `at`:

```c++
template <typename It, bool condition>
struct at_impl<It, when<condition>> : default_ {
    template <typename ...Args>
    static constexpr auto apply(Args&& ...) = delete;
};
```

For lack of a clearly superior alternative, I'd rather stick with `hana::is_default`.
