### ISSUE TITLE
MAX_NUMBER_OF_MEMBERS

### ISSUE THREAD

**Issue by mjhurd** [boostorg/hana#376]
Hi, 

Boost Hana's wonderfulness is unavailable for some autogen structs from table work I'm working with. 

I have more than 62 columns - to be members -  of the table - to be struct.

Unfortunately, the ERB in hana/detail doesn't like the idea of more than 62 members in a struct. 

`MAX_NUMBER_OF_MEMBERS = (ENV["MAX_NUMBER_OF_MEMBERS"] || 40).to_i
    raise "MAX_NUMBER_OF_MEMBERS must be <= 62" if MAX_NUMBER_OF_MEMBERS > 62`

Pretty sensible for handcrafting but a bit limiting for my autogen work. Any thoughts on how best to raise the bar to 79 or 99 members?

Kind regards,

--Matt.

**Comment by ricejasonf** [comment]
It looks like the ERB is just generating preprocessor macros which have a limit to the amount of arguments that a macro can receive.

The docs for `Struct` show that you can implement `hana::accessors` for your type directly instead of using the macro. It's not very pretty, but if you are generating code heterogeneously (outside of c++) that probably doesn't matter.

See the examples below "Minimal Complete Definition" here: [Struct](http://boostorg.github.io/hana/group__group-Struct.html)

**Comment by mjhurd** [comment]
Thanks for the link to Struct. That'll do the job I need.

**Comment by ldionne** [comment]
I was away over the holidays. Reopening since I think we need a better solution. The ERB could generate the macros it needs for up to the right number of elements. In other words, we could lift the restriction that `MAX_NUMBER_OF_MEMBERS <= 62`.

**Comment by ldionne** [comment]
This should now be addressed. You can now generate `struct_macros.hpp` without any restriction on the number of members. This will be in Boost 1.67.
